const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const root=__dirname,port=Number(process.env.PORT)||8080;
if(!process.env.DATABASE_URL)console.warn('DATABASE_URL is not set. Keily needs Render PostgreSQL to start.');
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data))};
const makeToken=()=>crypto.randomBytes(32).toString('hex');
const makeHash=(value,salt=crypto.randomBytes(16).toString('hex'))=>({salt,hash:crypto.scryptSync(value,salt,64).toString('hex')});
const sameHash=(value,salt,hash)=>crypto.timingSafeEqual(Buffer.from(crypto.scryptSync(value||'',salt,64).toString('hex'),'hex'),Buffer.from(hash,'hex'));
const readBody=req=>new Promise((resolve,reject)=>{let raw='';req.on('data',chunk=>{raw+=chunk;if(raw.length>20000)req.destroy()});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid request'))}});req.on('error',reject)});
const publicUser=row=>({id:row.id,name:row.name,gender:row.gender,period:row.period_enabled});
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users (id VARCHAR(20) PRIMARY KEY,name VARCHAR(30) NOT NULL,gender VARCHAR(40) NOT NULL DEFAULT '',period_enabled BOOLEAN NOT NULL DEFAULT FALSE,password_salt TEXT NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY,user_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE TABLE IF NOT EXISTS friendships (user_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,friend_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(user_id,friend_id),CHECK(user_id<>friend_id));CREATE TABLE IF NOT EXISTS friend_requests (from_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,to_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(from_id,to_id),CHECK(from_id<>to_id));CREATE TABLE IF NOT EXISTS safe_profiles (user_id VARCHAR(20) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,period_plan JSONB NOT NULL DEFAULT '{}'::jsonb,emergency_contacts JSONB NOT NULL DEFAULT '{"risk":[],"nearby":[]}'::jsonb,water_done BOOLEAN NOT NULL DEFAULT FALSE,code_salt TEXT,code_hash TEXT,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());`)}
async function sessionUser(req){const value=req.headers.authorization?.replace('Bearer ','');if(!value)return null;const result=await pool.query('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1',[value]);return result.rows[0]||null}
async function askGemini(message){const key=process.env.GEMINI_API_KEY,model=process.env.GEMINI_MODEL||'gemini-3.8-flash';if(!key)throw new Error('Keily AI is not configured yet. Add GEMINI_API_KEY in Render.');const system='You are Keily, a warm, concise safety and wellbeing companion. Reply in plain, supportive language. Never claim to be a doctor, therapist, emergency service, or to have contacted anyone. For immediate danger, encourage the user to call their local emergency number and use Keily Safe Space. Do not provide diagnoses, medication instructions, or shame the user. Keep replies under 110 words.';const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:message}]}],generationConfig:{temperature:.7,maxOutputTokens:260}})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||'Gemini could not answer right now.');const reply=payload.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join('').trim();if(!reply)throw new Error('Keily did not receive a reply.');return reply}
async function getProfile(id){const result=await pool.query('SELECT period_plan,emergency_contacts,water_done,code_hash IS NOT NULL AS has_code_word FROM safe_profiles WHERE user_id=$1',[id]);return result.rows[0]||{period_plan:{},emergency_contacts:{risk:[],nearby:[]},water_done:false,has_code_word:false}}
const validContacts=list=>Array.isArray(list)&&list.filter(x=>x&&typeof x.name==='string'&&typeof x.phone==='string').slice(0,50).map(x=>({name:x.name.trim().slice(0,60),phone:x.phone.trim().slice(0,30)}));
async function api(req,res,url){let input,user,id,result;if(req.method==='POST'&&url.pathname==='/api/register'){input=await readBody(req);id=(input.id||'').trim().toLowerCase();if(!/^[a-z0-9._-]{3,20}$/.test(id)||!input.name?.trim()||!input.password||input.password.length<8)return json(res,400,{error:'Use a name, a valid ID, and an 8-character password.'});const password=makeHash(input.password);try{await pool.query('INSERT INTO users (id,name,gender,period_enabled,password_salt,password_hash) VALUES ($1,$2,$3,$4,$5,$6)',[id,input.name.trim().slice(0,30),(input.gender||'').slice(0,40),!!input.period,password.salt,password.hash]);await pool.query('INSERT INTO safe_profiles (user_id) VALUES ($1)',[id])}catch(error){if(error.code==='23505')return json(res,409,{error:'That Keily ID is already taken.'});throw error}const session=makeToken();await pool.query('INSERT INTO sessions (token,user_id) VALUES ($1,$2)',[session,id]);return json(res,201,{token:session,user:{id,name:input.name.trim(),gender:input.gender||'',period:!!input.period}})}
if(req.method==='POST'&&url.pathname==='/api/login'){input=await readBody(req);result=await pool.query('SELECT * FROM users WHERE id=$1',[(input.id||'').trim().toLowerCase()]);user=result.rows[0];if(!user||!sameHash(input.password,user.password_salt,user.password_hash))return json(res,401,{error:'That Keily ID or password is incorrect.'});const session=makeToken();await pool.query('INSERT INTO sessions (token,user_id) VALUES ($1,$2)',[session,user.id]);return json(res,200,{token:session,user:publicUser(user)})}
user=await sessionUser(req);if(!user)return json(res,401,{error:'Please sign in.'});
if(req.method==='POST'&&url.pathname==='/api/keily-chat'){input=await readBody(req);const message=(input.message||'').trim();if(!message||message.length>1200)return json(res,400,{error:'Please send a message of up to 1,200 characters.'});try{return json(res,200,{reply:await askGemini(message)})}catch(error){return json(res,502,{error:error.message})}}
if(req.method==='GET'&&url.pathname==='/api/me'){const friends=await pool.query('SELECT u.id,u.name,u.gender,u.period_enabled FROM friendships f JOIN users u ON u.id=f.friend_id WHERE f.user_id=$1',[user.id]);const incoming=await pool.query('SELECT u.id,u.name,u.gender,u.period_enabled FROM friend_requests r JOIN users u ON u.id=r.from_id WHERE r.to_id=$1',[user.id]);const outgoing=await pool.query('SELECT u.id,u.name,u.gender,u.period_enabled FROM friend_requests r JOIN users u ON u.id=r.to_id WHERE r.from_id=$1',[user.id]);return json(res,200,{user:publicUser(user),friends:friends.rows.map(publicUser),incoming:incoming.rows.map(publicUser),outgoing:outgoing.rows.map(publicUser)})}
if(req.method==='GET'&&url.pathname==='/api/safe-profile')return json(res,200,await getProfile(user.id));
if(req.method==='PUT'&&url.pathname==='/api/safe-profile'){input=await readBody(req);const periodPlan=input.periodPlan&&typeof input.periodPlan==='object'?{last:String(input.periodPlan.last||'').slice(0,20),length:Math.max(21,Math.min(40,Number(input.periodPlan.length)||28)),pad:!!input.periodPlan.pad}:{};const contacts=input.emergencyContacts&&typeof input.emergencyContacts==='object'?{risk:validContacts(input.emergencyContacts.risk).slice(0,4),nearby:validContacts(input.emergencyContacts.nearby)}:{risk:[],nearby:[]};await pool.query('INSERT INTO safe_profiles (user_id,period_plan,emergency_contacts,water_done) VALUES ($1,$2,$3,$4) ON CONFLICT (user_id) DO UPDATE SET period_plan=EXCLUDED.period_plan,emergency_contacts=EXCLUDED.emergency_contacts,water_done=EXCLUDED.water_done,updated_at=now()',[user.id,periodPlan,contacts,!!input.waterDone]);return json(res,200,{ok:true})}
if(req.method==='POST'&&url.pathname==='/api/code-word'){input=await readBody(req);const code=(input.codeWord||'').trim();if(code.length<3||code.length>80)return json(res,400,{error:'Use a code word between 3 and 80 characters.'});const secret=makeHash(code.toLowerCase());await pool.query('UPDATE safe_profiles SET code_salt=$2,code_hash=$3,updated_at=now() WHERE user_id=$1',[user.id,secret.salt,secret.hash]);return json(res,200,{ok:true,hasCodeWord:true})}
if(req.method==='POST'&&url.pathname==='/api/check-code-word'){input=await readBody(req);result=await pool.query('SELECT code_salt,code_hash FROM safe_profiles WHERE user_id=$1',[user.id]);const profile=result.rows[0];const valid=!!profile?.code_hash&&sameHash((input.spoken||'').trim().toLowerCase(),profile.code_salt,profile.code_hash);return json(res,200,{valid})}
if(req.method==='POST'&&url.pathname==='/api/requests'){input=await readBody(req);id=(input.id||'').trim().toLowerCase();if(id===user.id)return json(res,400,{error:'You cannot add yourself.'});result=await pool.query('SELECT id FROM users WHERE id=$1',[id]);if(!result.rowCount)return json(res,404,{error:'No Keily user has that ID.'});result=await pool.query('SELECT 1 FROM friendships WHERE user_id=$1 AND friend_id=$2',[user.id,id]);if(result.rowCount)return json(res,400,{error:'You are already friends.'});try{await pool.query('INSERT INTO friend_requests (from_id,to_id) VALUES ($1,$2)',[user.id,id])}catch(error){if(error.code==='23505')return json(res,400,{error:'Request already sent.'});throw error}return json(res,201,{message:'Friend request sent.'})}
if(req.method==='POST'&&url.pathname==='/api/respond'){input=await readBody(req);id=(input.from||'').trim().toLowerCase();result=await pool.query('DELETE FROM friend_requests WHERE from_id=$1 AND to_id=$2 RETURNING from_id',[id,user.id]);if(!result.rowCount)return json(res,404,{error:'This request no longer exists.'});if(input.action==='accept'){await pool.query('INSERT INTO friendships (user_id,friend_id) VALUES ($1,$2),($2,$1) ON CONFLICT DO NOTHING',[user.id,id])}return json(res,200,{message:input.action==='accept'?'Friend request accepted.':'Friend request rejected.'})}
return json(res,404,{error:'Not found'})}
http.createServer(async(req,res)=>{const url=new URL(req.url,'http://local');try{if(url.pathname.startsWith('/api/'))return await api(req,res,url);const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root)||!fs.existsSync(file))return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream'});if(path.basename(file)==='index.html')return res.end(fs.readFileSync(file,'utf8').replace('<script src="app.js"></script>','<script src="app.js"></script><script src="network.js"></script>'));fs.createReadStream(file).pipe(res)}catch(error){console.error(error);json(res,500,{error:'Something went wrong. Please try again.'})}}).listen(port,'0.0.0.0',async()=>{try{await init();console.log(`Keily ready on port ${port}`)}catch(error){console.error('PostgreSQL connection failed:',error.message);process.exit(1)}});
